apiVersion: v1
kind: Service
metadata:
  name: flaskdataservice
  namespace: im 
spec:
  type: NodePort
  selector:
    app: flaskdataapp
  ports:
  - port: 5000
    targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: ldatservice
  namespace: im
spec:
  type: NodePort
  selector:
    app: ldatapp
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: flaskdataapp
  namespace: im
spec:
  selector:
    matchLabels:
      app: flaskdataapp
  serviceName: flaskdataservice
  replicas: 1
  template:
    metadata:
      labels:
        app: flaskdataapp
    spec:
      containers:
      - name: flaskdataapp
        image: ncar-im-0.rc.unr.edu/mqttlistenservice
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: regcred
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ldatapp
  namespace: im
spec:
  selector:
    matchLabels:
      app: ldatapp
  serviceName: ldatservice
  replicas: 1
  template:
    metadata:
      labels:
        app: ldatapp
    spec:
      containers:
      - name: ldatapp
        image: ncar-im-0.rc.unr.edu/mqttwebapp
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred